### ISSUE TITLE
VCV crashes when loading artificialcolors Chord4Roy on linux

### ISSUE THREAD

**Issue by sc3sc3** [gwygonik/acModules#2]
Hi,
thanks for your work.

trying to load **artificialcolors Chord4Roy** on linux ( UbuntuStudio 24.04 ) crashes VCV
zoom factor in VCV is 136%

[16.052 info src/app/Browser.cpp:89 chooseModel] Creating module artificialcolors Chord4Roy
[16.052 info src/app/Browser.cpp:93 chooseModel] Creating module widget artificialcolors Chord4Roy
[16.066 fatal adapters/standalone.cpp:49 fatalSignalHandler] Fatal signal 11. Stack trace:
27: ./Rack() [0x40444d]
26: /lib/x86_64-linux-gnu/libc.so.6(+0x45320)
25: /lib/x86_64-linux-gnu/libc.so.6(+0x18b75d)
24: ./libRack.so(nvgText+0x653)
23: /home/RPR/.local/share/Rack2/plugins-lin-x64/acModules/plugin.so(Chord4RoyDisplay<Chord4Roy>::drawLayer(rack::widget::Widget::DrawArgs const&, int)+0x116)
22: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x159)
21: ./libRack.so(rack::widget::Widget::drawLayer(rack::widget::Widget::DrawArgs const&, int)+0xc7)
20: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x159)
19: ./libRack.so(rack::widget::Widget::drawLayer(rack::widget::Widget::DrawArgs const&, int)+0xc7)
18: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x159)
17: ./libRack.so(rack::widget::Widget::drawLayer(rack::widget::Widget::DrawArgs const&, int)+0xc7)
16: ./libRack.so(rack::app::RackWidget::draw(rack::widget::Widget::DrawArgs const&)+0x66)
15: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
14: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
13: ./libRack.so(rack::widget::ZoomWidget::draw(rack::widget::Widget::DrawArgs const&)+0x4c)
12: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
11: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
10: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
9: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
8: ./libRack.so(rack::ui::ScrollWidget::draw(rack::widget::Widget::DrawArgs const&)+0x34)
7: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
6: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
5: ./libRack.so(rack::window::Window::step()+0x74c)
4: ./libRack.so(rack::window::Window::run()+0x28)
3: ./Rack(main+0xec2)
2: /lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca)
1: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b)
0: ./Rack() [0x404379]

**Comment by gwygonik** [comment]
Hi. Thanks for the log details. I _do_ test on Linux (Ubuntu 22.04.5 LTS) so this report doesn't make me happy. ☹️  

I downloaded and ran a new instance of Rack2, installed the plugins from the library and WAS able to reproduce this error, but only _the very first time I tried to add the plugin_ to a patch; I could not reproduce it after that first install/run. 

I attached a screenshot of Rack2 in Linux with all the acModules running, so it _can_ work, but I don't know why it doesn't on first install. 

I would ask if you could try again on a blank patch and see if it does this every time, or if you can reproduce it in some combination with a module you were using at the time? Thanks!
![Screenshot from 2024-10-25 16-03-24](https://github.com/user-attachments/assets/8a7ca8c8-11c0-45dd-bcd0-3a9df46e0d2c)

**Comment by gwygonik** [comment]
I pushed an update that might address this issue. It will take a few days to get through the pipeline. Will circle back when it gets approved.

**Comment by sc3sc3** [comment]
Ok, thank you.
Let me know if i need to test something

**Comment by gwygonik** [comment]
I've revamped my build system and have tested 2.0.2 on Linux and Windows. The update DOES seem to fix the issue on Linux, so you should be good once it gets through the Rack release pipeline! 

However, if it _doesn't_ for some strange reason, 2.0.3 which fixes the Windows crash for the same module should do it, but that will come later in the week.

**Comment by gwygonik** [comment]
2.0.2 was in the update today to VCV library, so it should update and fix this issue. I'll wait close this should it not fix it for you. Also, 2.0.3 is heading to the update process which fixes this module on Windows, in case there are still outstanding issues. Sorry for the problems! Thanks for your help!

**Comment by sc3sc3** [comment]
I just updated to the new version, and still the same crash occurs.
I'll wait for version 2.0.3 :-)

**Comment by sc3sc3** [comment]
Strange thing is the crash only occurs when adding Chord4Roy.
When adding the other modules of your collection, there is no crash.

**Comment by gwygonik** [comment]
Cool. Thanks for the quick update! 😃  Then it seems like 2.0.3 (which I just submitted) might also fix for you, as that was the only one of the 2.0.2 updates that crashed Windows. It's an odd issue.

**Comment by gwygonik** [comment]
2.0.4 got through the process and is in the library. I found another cause of the crash and tried to work around it. Hopefully it works now for you (and others)! Please let me know after you've had an opportunity to update and try it. Thanks again for your help and patience!

**Comment by sc3sc3** [comment]
The module can be added and works.
Thanks for your work and persistence :-)

**Comment by gwygonik** [comment]
Yay! We'll close this then. I've added a few test cases to my routine, so between the multiple platforms and the tests, I hope to have less crashes overall. 🤞 Thanks again!
